version: '3.1'

services:
  mongo:
    image: mongo:6.0.10
    ports:
      - 27017:27017

  message-app:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/message
      - PORT=8000